# Generated by Django 3.0.3 on 2020-02-05 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCarrera', models.CharField(max_length=500)),
                ('codigo', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMateria', models.CharField(max_length=500)),
                ('tag', models.CharField(max_length=200)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRol', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Termino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTermino', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=500)),
                ('usuario', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('estado', models.BooleanField()),
                ('correo', models.CharField(max_length=500)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Materia')),
                ('termino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Termino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNoticia', models.CharField(max_length=500)),
                ('descrNoticia', models.CharField(max_length=500)),
                ('creadoFecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('termino', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('idRegistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Registro')),
            ],
        ),
    ]
