# Generated by Django 3.0.3 on 2020-02-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=500)),
                ('correo', models.CharField(max_length=500)),
                ('tema', models.CharField(max_length=500)),
                ('mensaje', models.CharField(max_length=800)),
            ],
        ),
    ]
